name: Test2

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || ! failure()
    steps:
      - name: "step1"
        run: |
          echo "Hello World from step1"
        shell: bash
      - name: "Fail"
        run: |
          exit 1
        shell: bash

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ ! failure() }}
    steps:
      - name: "step2"
        run: |
          echo "Hello World from step2"
        shell: bash

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: ${{ ! failure() }}
    steps:
      - name: "step3"
        run: |
          echo "Hello World from step3"
        shell: bash
