name: Test4

on:
  workflow_dispatch:
    inputs:
      enable_job1:
        description: 'job1を実行するかどうか'
        required: true
        default: true
        type: boolean

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ inputs.enable_job1 == true }}
    steps:
      - name: "step1"
        run: |
          echo "Hello World from step1"
        shell: bash
      - name: "Fail"
        run: |
          exit 1
        shell: bash

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ ! cancelled() && ! failure() }}
    steps:
      - name: "step2"
        run: |
          echo "Hello World from step2"
        shell: bash

  job3:
    runs-on: ubuntu-latest
    needs: job2
    if: ${{ ! cancelled() && ! failure() }}
    steps:
      - name: "step3"
        run: |
          echo "Hello World from step3"
        shell: bash
